executed: '2024-12-26T00:34:05.296Z'
results:
  - code: openapi-external-docs-error
    message: OpenAPI MUST Have External Documentation
    path: []
    severity: 0
    range:
      start:
        line: 0
        character: 0
      end:
        line: 388
        character: 13
  - code: openapi-no-api-in-path-error
    message: No API in Path
    path:
      - paths
      - /company/logo/get
    severity: 0
    range:
      start:
        line: 7
        character: 20
      end:
        line: 172
        character: 26
  - code: openapi-no-path-trailing-slash-info
    message: Path Trailing Slash
    path:
      - paths
      - /company/logo/get
    severity: 2
    range:
      start:
        line: 7
        character: 20
      end:
        line: 172
        character: 26
  - code: openapi-version-in-path-info
    message: Version in Path
    path:
      - paths
      - /company/logo/get
    severity: 2
    range:
      start:
        line: 7
        character: 20
      end:
        line: 172
        character: 26
  - code: openapi-no-request-body-on-get-info
    message: GET Request Body
    path:
      - paths
      - /company/logo/get
      - get
    severity: 2
    range:
      start:
        line: 8
        character: 8
      end:
        line: 172
        character: 26
  - code: openapi-operation-security-definitions-error
    message: Operations MUST Have a Security Definition
    path:
      - paths
      - /company/logo/get
      - get
    severity: 0
    range:
      start:
        line: 8
        character: 8
      end:
        line: 172
        character: 26
  - code: openapi-operations-tags-info
    message: Operations Has Tags
    path:
      - paths
      - /company/logo/get
      - get
      - tags
    severity: 2
    range:
      start:
        line: 9
        character: 11
      end:
        line: 11
        character: 14
  - code: openapi-operations-tags-upper-case-info
    message: Operation Tag Names Have First Letter in Each Word Capitalized
    path:
      - paths
      - /company/logo/get
      - get
      - tags
      - '0'
    severity: 2
    range:
      start:
        line: 10
        character: 10
      end:
        line: 10
        character: 17
  - code: openapi-operations-tags-upper-case-info
    message: Operation Tag Names Have First Letter in Each Word Capitalized
    path:
      - paths
      - /company/logo/get
      - get
      - tags
      - '1'
    severity: 2
    range:
      start:
        line: 11
        character: 10
      end:
        line: 11
        character: 14
  - code: openapi-operations-operation-ids-camel-case-error
    message: Operation Identifier MUST Be camelCase
    path:
      - paths
      - /company/logo/get
      - get
      - operationId
    severity: 0
    range:
      start:
        line: 12
        character: 19
      end:
        line: 12
        character: 39
  - code: openapi-operations-operation-ids-camel-case-info
    message: Operation Identifier Is camelCase
    path:
      - paths
      - /company/logo/get
      - get
      - operationId
    severity: 2
    range:
      start:
        line: 12
        character: 19
      end:
        line: 12
        character: 39
  - code: openapi-operations-operation-ids-info
    message: Operation Has Identifier
    path:
      - paths
      - /company/logo/get
      - get
      - operationId
    severity: 2
    range:
      start:
        line: 12
        character: 19
      end:
        line: 12
        character: 39
  - code: openapi-operations-summary-info
    message: Operation Has a Summary
    path:
      - paths
      - /company/logo/get
      - get
      - summary
    severity: 2
    range:
      start:
        line: 24
        character: 15
      end:
        line: 24
        character: 45
  - code: openapi-operations-summary-period-none-error
    message: Operation MUST Not Have a Period.
    path:
      - paths
      - /company/logo/get
      - get
      - summary
    severity: 0
    range:
      start:
        line: 24
        character: 15
      end:
        line: 24
        character: 45
  - code: openapi-operations-description-info
    message: Operation Has Description
    path:
      - paths
      - /company/logo/get
      - get
      - description
    severity: 2
    range:
      start:
        line: 25
        character: 19
      end:
        line: 39
        character: 49
  - code: openapi-operations-description-length-error
    message: Operation Description MUST Be Less Than 250 Characters
    path:
      - paths
      - /company/logo/get
      - get
      - description
    severity: 1
    range:
      start:
        line: 25
        character: 19
      end:
        line: 39
        character: 49
  - code: openapi-parameters-componentized-error
    message: Parameters MUST use components $ref.
    path:
      - paths
      - /company/logo/get
      - get
      - parameters
      - '0'
    severity: 0
    range:
      start:
        line: 41
        character: 10
      end:
        line: 50
        character: 64
  - code: openapi-parameters-componentized-error
    message: Parameters MUST use components $ref.
    path:
      - paths
      - /company/logo/get
      - get
      - parameters
      - '1'
    severity: 0
    range:
      start:
        line: 51
        character: 10
      end:
        line: 65
        character: 28
  - code: openapi-parameters-componentized-error
    message: Parameters MUST use components $ref.
    path:
      - paths
      - /company/logo/get
      - get
      - parameters
      - '2'
    severity: 0
    range:
      start:
        line: 66
        character: 10
      end:
        line: 77
        character: 20
  - code: openapi-parameters-componentized-error
    message: Parameters MUST use components $ref.
    path:
      - paths
      - /company/logo/get
      - get
      - parameters
      - '3'
    severity: 0
    range:
      start:
        line: 78
        character: 10
      end:
        line: 88
        character: 90
  - code: openapi-response-get-400-status-code-error
    message: GET Responses MUST Have 400 Status Codes
    path:
      - paths
      - /company/logo/get
      - get
      - responses
    severity: 0
    range:
      start:
        line: 89
        character: 16
      end:
        line: 172
        character: 26
  - code: openapi-response-get-401-status-code-error
    message: GET Responses Has 401 Status Code
    path:
      - paths
      - /company/logo/get
      - get
      - responses
    severity: 0
    range:
      start:
        line: 89
        character: 16
      end:
        line: 172
        character: 26
  - code: openapi-response-get-403-status-code-error
    message: GET Responses Has 403 Status Code
    path:
      - paths
      - /company/logo/get
      - get
      - responses
    severity: 0
    range:
      start:
        line: 89
        character: 16
      end:
        line: 172
        character: 26
  - code: openapi-response-get-429-status-code-error
    message: GET Responses Has 429 Status Code
    path:
      - paths
      - /company/logo/get
      - get
      - responses
    severity: 0
    range:
      start:
        line: 89
        character: 16
      end:
        line: 172
        character: 26
  - code: openapi-response-get-500-status-code-error
    message: GET Responses MUST Have 500 Status Code
    path:
      - paths
      - /company/logo/get
      - get
      - responses
    severity: 0
    range:
      start:
        line: 89
        character: 16
      end:
        line: 172
        character: 26
  - code: openapi-response-get-200-content-error
    message: GET 200 Response MUST Have Content.
    path:
      - paths
      - /company/logo/get
      - get
      - responses
      - '200'
    severity: 0
    range:
      start:
        line: 90
        character: 14
      end:
        line: 172
        character: 26
  - code: openapi-response-get-200-status-code-info
    message: GET Responses Has 200 Status Codes
    path:
      - paths
      - /company/logo/get
      - get
      - responses
      - '200'
    severity: 2
    range:
      start:
        line: 90
        character: 14
      end:
        line: 172
        character: 26
  - code: openapi-response-get-200-description-info
    message: GET 200 Response has description.
    path:
      - paths
      - /company/logo/get
      - get
      - responses
      - '200'
      - description
    severity: 2
    range:
      start:
        line: 91
        character: 23
      end:
        line: 91
        character: 42
  - code: openapi-info-contact-error
    message: Info MUST Have Contact Object
    path:
      - info
    severity: 0
    range:
      start:
        line: 173
        character: 5
      end:
        line: 176
        character: 14
  - code: openapi-info-license-error
    message: Info MUST Have License
    path:
      - info
    severity: 0
    range:
      start:
        line: 173
        character: 5
      end:
        line: 176
        character: 14
  - code: openapi-info-terms-of-service-error
    message: Info MUST Have Terms of Service
    path:
      - info
    severity: 0
    range:
      start:
        line: 173
        character: 5
      end:
        line: 176
        character: 14
  - code: openapi-info-title-info
    message: Info Has Title
    path:
      - info
      - title
    severity: 2
    range:
      start:
        line: 174
        character: 9
      end:
        line: 174
        character: 53
  - code: openapi-info-title-upper-case-info
    message: Info Title MUST Have First Characters Capitalized
    path:
      - info
      - title
    severity: 2
    range:
      start:
        line: 174
        character: 9
      end:
        line: 174
        character: 53
  - code: openapi-info-description-info
    message: Info Has Description
    path:
      - info
      - description
    severity: 2
    range:
      start:
        line: 175
        character: 15
      end:
        line: 175
        character: 59
  - code: openapi-info-version-info
    message: Info Has Version
    path:
      - info
      - version
    severity: 2
    range:
      start:
        line: 176
        character: 11
      end:
        line: 176
        character: 14
  - code: openapi-tags-object-info
    message: OpenAPIs Have a Tag Object
    path:
      - tags
    severity: 2
    range:
      start:
        line: 180
        character: 5
      end:
        line: 182
        character: 34
  - code: openapi-tags-name-info
    message: Tags Have a Name
    path:
      - tags
      - '0'
      - name
    severity: 2
    range:
      start:
        line: 181
        character: 10
      end:
        line: 181
        character: 19
  - code: openapi-tags-description-info
    message: Tags Have a Description
    path:
      - tags
      - '0'
      - description
    severity: 2
    range:
      start:
        line: 182
        character: 17
      end:
        line: 182
        character: 34
