openapi: 3.2.0
info:
  version: 1.1.0
  title: FactSet Search Answers API
  contact:
    name: FactSet Search Team
    email: FactSearch.Team@factset.com
  description: '

    The FactSet Search Answers API provides answers to search queries,

    reflecting the data shown within FactSet Search Answers.'
servers:
- url: https://api.factset.com
security:
- Basic: []
tags:
- name: Answers
paths:
  /search/answers/v1/data:
    get:
      summary: Fetch Factset Answer in Data Format
      tags:
      - Answers
      description: Returns an answer to the specified query (if a valid answer exists). Returns the answer data only (as JSON), without any markup information.
      operationId: searchForDataAnswer
      parameters:
      - $ref: '#/components/parameters/Query'
      - $ref: '#/components/parameters/ConsumingApplication'
      responses:
        '200':
          description: Request was successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataAnswerSuccessResponse'
        '400':
          description: Missing or empty query.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnswerFailureResponse'
        '401':
          description: Missing or invalid authentication.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnswerFailureResponse'
        '500':
          description: Unhandled error occurred while processing the request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnswerFailureResponse'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  schemas:
    ValueChange:
      type: object
      properties:
        absoluteChange:
          type: string
          example: example_value
        percentageChange:
          type: string
          example: example_value
        color:
          $ref: '#/components/schemas/ChangeColor'
    AnswerFailureResponse:
      type: object
      required:
      - errors
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
          example: []
    RankedTableEntity:
      type: object
      properties:
        name:
          type: string
          example: Example Title
        identifier:
          type: string
          example: example_value
    LabelValueChangeLabelValueChangeTemplateData:
      allOf:
      - $ref: '#/components/schemas/TemplateWithLinks'
      - type: object
        properties:
          value:
            type: string
          label:
            type: string
          valueChange:
            $ref: '#/components/schemas/ValueChange'
          value2:
            type: string
          label2:
            type: string
    ValueChangeDateLabelAnswer:
      allOf:
      - $ref: '#/components/schemas/AnswerWithTitle'
      - type: object
        required:
        - templateData
        properties:
          templateData:
            $ref: '#/components/schemas/ValueChangeDateLabelTemplateData'
    PercentChange:
      type: object
      properties:
        change:
          type: string
          example: example_value
        color:
          $ref: '#/components/schemas/ChangeColor'
    InstrumentID:
      type: object
      properties:
        BBG:
          type: string
          example: example_value
        CUSIP:
          type: string
          example: example_value
        FDS_ID:
          type: string
          example: '500123'
        FDS_TICKER_REGION:
          type: string
          example: example_value
        FDS_TICKER_EXCHANGE:
          type: string
          example: example_value
        FIGI:
          type: string
          example: example_value
        ISIN:
          type: string
          example: example_value
        PERMID:
          type: string
          example: '500123'
        RIC:
          type: string
          example: example_value
        SEDOL:
          type: string
          example: example_value
        ticker:
          type: string
          example: example_value
    TableTableTemplateData:
      allOf:
      - $ref: '#/components/schemas/TemplateWithLinks'
      - type: object
        properties:
          table1:
            $ref: '#/components/schemas/Table'
          table2:
            $ref: '#/components/schemas/Table'
    ValueColor:
      type: string
      enum:
      - colorNone
      - colorBuy
      - colorHold
      - colorSell
      - colorOverweight
      - colorUnderweight
    TextBlockFootingAnswer:
      allOf:
      - $ref: '#/components/schemas/AnswerWithTitle'
      - type: object
        required:
        - templateData
        properties:
          templateData:
            $ref: '#/components/schemas/TextBlockFootingTemplateData'
    ColoredValueLabelDateTemplateData:
      allOf:
      - $ref: '#/components/schemas/TemplateWithLinks'
      - type: object
        properties:
          value:
            $ref: '#/components/schemas/ColoredValue'
          label:
            type: string
          date:
            type: string
    TemplateWithLinks:
      allOf:
      - $ref: '#/components/schemas/Template'
      - type: object
        required:
        - headline
        properties:
          applicationLinks:
            type: array
            items:
              $ref: '#/components/schemas/ApplicationLink'
    ErrorSource:
      type: object
      properties:
        pointer:
          type: string
          example: example_value
        parameter:
          type: string
          example: example_value
    DataAnswerData:
      oneOf:
      - $ref: '#/components/schemas/LinkTextBlockAnswer'
      - $ref: '#/components/schemas/TextBlockFootingAnswer'
      - $ref: '#/components/schemas/PercentChangeLabelAnswer'
      - $ref: '#/components/schemas/ValueChangeDateLabelAnswer'
      - $ref: '#/components/schemas/RankedTableAnswer'
      - $ref: '#/components/schemas/TableAnswer'
      - $ref: '#/components/schemas/TableTableAnswer'
      - $ref: '#/components/schemas/ValueLabelAnswer'
      - $ref: '#/components/schemas/ValueLabelDateAnswer'
      - $ref: '#/components/schemas/ColoredValueLabelDateAnswer'
      - $ref: '#/components/schemas/ValueLabelDateTextBlockAnswer'
      - $ref: '#/components/schemas/ValueLabelDateDataPairListAnswer'
      - $ref: '#/components/schemas/LabelValueChangeLabelValueChangeAnswer'
      - $ref: '#/components/schemas/AnswerWithoutData'
      - $ref: '#/components/schemas/NoAnswersFound'
      discriminator:
        propertyName: template
        mapping:
          LinkTextBlockTemplate: '#/components/schemas/LinkTextBlockAnswer'
          TextBlockFootingTemplate: '#/components/schemas/TextBlockFootingAnswer'
          PercentChangeLabelTemplate: '#/components/schemas/PercentChangeLabelAnswer'
          ValueChangeDateLabelTemplate: '#/components/schemas/ValueChangeDateLabelAnswer'
          RankedTableTemplate: '#/components/schemas/RankedTableAnswer'
          TableTemplate: '#/components/schemas/TableAnswer'
          TableTableTemplate: '#/components/schemas/TableTableAnswer'
          ValueLabelTemplate: '#/components/schemas/ValueLabelAnswer'
          ValueLabelDateTemplate: '#/components/schemas/ValueLabelDateAnswer'
          ColoredValueLabelDateTemplate: '#/components/schemas/ColoredValueLabelDateAnswer'
          ValueLabelDateTextBlockTemplate: '#/components/schemas/ValueLabelDateTextBlockAnswer'
          ValueLabelDateDataPairListTemplate: '#/components/schemas/ValueLabelDateDataPairListAnswer'
          LabelValueChangeLabelValueChangeTemplate: '#/components/schemas/LabelValueChangeLabelValueChangeAnswer'
          AnswerWithoutDataTemplate: '#/components/schemas/AnswerWithoutData'
          NoAnswerTemplate: '#/components/schemas/NoAnswersFound'
    TitledTextBlock:
      type: object
      properties:
        title:
          type: string
          example: Example Title
        content:
          type: string
          example: example_value
    ValueLabelDateDataPairListTemplateData:
      allOf:
      - $ref: '#/components/schemas/TemplateWithLinks'
      - type: object
        properties:
          value:
            type: string
          label:
            type: string
          date:
            type: string
          list:
            type: array
            items:
              $ref: '#/components/schemas/DataPair'
    RankedTableTemplateData:
      allOf:
      - $ref: '#/components/schemas/Template'
      - type: object
        properties:
          table:
            $ref: '#/components/schemas/RankedTable'
    LabelValueChangeLabelValueChangeAnswer:
      allOf:
      - $ref: '#/components/schemas/AnswerWithTitle'
      - type: object
        required:
        - templateData
        properties:
          templateData:
            $ref: '#/components/schemas/LabelValueChangeLabelValueChangeTemplateData'
    RankedTableAnswer:
      allOf:
      - $ref: '#/components/schemas/AnswerWithTitle'
      - type: object
        required:
        - templateData
        properties:
          templateData:
            $ref: '#/components/schemas/RankedTableTemplateData'
    NoAnswersBase:
      allOf:
      - $ref: '#/components/schemas/DataAnswer'
      - type: object
        required:
        - message
        properties:
          message:
            type: string
    Template:
      type: object
      required:
      - headline
      properties:
        headline:
          type: string
          example: example_value
        footer:
          type: string
          example: example_value
        fdc3Context:
          $ref: '#/components/schemas/Fdc3Context'
    TextBlockFootingTemplateData:
      allOf:
      - $ref: '#/components/schemas/TemplateWithLinks'
      - type: object
        properties:
          body:
            type: string
          footing:
            $ref: '#/components/schemas/TitledTextBlock'
    LinkTextBlockAnswer:
      allOf:
      - $ref: '#/components/schemas/AnswerWithTitle'
      - type: object
        required:
        - templateData
        properties:
          templateData:
            $ref: '#/components/schemas/LinkTextBlockTemplateData'
    AnswerWithTitle:
      allOf:
      - $ref: '#/components/schemas/DataAnswer'
      - type: object
        required:
        - title
        properties:
          title:
            type: string
    ColoredValue:
      type: object
      properties:
        text:
          type: string
          example: example_value
        color:
          $ref: '#/components/schemas/ValueColor'
    Fdc3Country:
      type: object
      required:
      - type
      - name
      properties:
        type:
          type: string
          example: example_value
        name:
          type: string
          example: Example Title
        id:
          $ref: '#/components/schemas/CountryID'
    ValueLabelDateTextBlockTemplateData:
      allOf:
      - $ref: '#/components/schemas/TemplateWithLinks'
      - type: object
        properties:
          value:
            type: string
          label:
            type: string
          date:
            type: string
          text:
            type: string
    TableTemplateData:
      allOf:
      - $ref: '#/components/schemas/TemplateWithLinks'
      - type: object
        properties:
          table:
            $ref: '#/components/schemas/Table'
    ErrorLink:
      type: object
      required:
      - about
      properties:
        about:
          type: string
          example: example_value
    ChangeColor:
      type: string
      enum:
      - colorNeutral
      - colorPositive
      - colorNegative
    DataAnswerSuccessResponse:
      type: object
      required:
      - data
      properties:
        data:
          $ref: '#/components/schemas/DataAnswerData'
    RankedTable:
      type: object
      required:
      - rows
      properties:
        headers:
          type: array
          items:
            type: string
          example: []
        rows:
          type: array
          items:
            $ref: '#/components/schemas/RankedTableRow'
          example: []
    ValueChangeDateLabelTemplateData:
      allOf:
      - $ref: '#/components/schemas/TemplateWithLinks'
      - type: object
        properties:
          value:
            type: string
          valueChange:
            $ref: '#/components/schemas/ValueChange'
          date:
            type: string
          label:
            type: string
    DataAnswer:
      type: object
      required:
      - template
      properties:
        template:
          type: string
          example: example_value
    TableTableAnswer:
      allOf:
      - $ref: '#/components/schemas/AnswerWithTitle'
      - type: object
        required:
        - templateData
        properties:
          templateData:
            $ref: '#/components/schemas/TableTableTemplateData'
    PercentChangeLabelTemplateData:
      allOf:
      - $ref: '#/components/schemas/TemplateWithLinks'
      - type: object
        properties:
          percentChange:
            $ref: '#/components/schemas/PercentChange'
          label:
            type: string
    Error:
      type: object
      required:
      - id
      - code
      - title
      properties:
        id:
          type: string
          example: abc123
        code:
          type: string
          example: example_value
        title:
          type: string
          example: Example Title
        links:
          $ref: '#/components/schemas/ErrorLink'
        detail:
          type: string
          example: example_value
        source:
          $ref: '#/components/schemas/ErrorSource'
    ValueLabelDateDataPairListAnswer:
      allOf:
      - $ref: '#/components/schemas/AnswerWithTitle'
      - type: object
        required:
        - templateData
        properties:
          templateData:
            $ref: '#/components/schemas/ValueLabelDateDataPairListTemplateData'
    PercentChangeLabelAnswer:
      allOf:
      - $ref: '#/components/schemas/AnswerWithTitle'
      - type: object
        required:
        - templateData
        properties:
          templateData:
            $ref: '#/components/schemas/PercentChangeLabelTemplateData'
    DataPair:
      type: object
      required:
      - value
      - label
      properties:
        value:
          type: string
          example: example_value
        label:
          type: string
          example: Example Title
    LinkTextBlockTemplateData:
      allOf:
      - $ref: '#/components/schemas/TemplateWithLinks'
      - type: object
        properties:
          link:
            type: string
          text:
            type: string
    ValueLabelTemplateData:
      allOf:
      - $ref: '#/components/schemas/TemplateWithLinks'
      - type: object
        properties:
          value:
            type: string
          label:
            type: string
    TableAnswer:
      allOf:
      - $ref: '#/components/schemas/AnswerWithTitle'
      - type: object
        required:
        - templateData
        properties:
          templateData:
            $ref: '#/components/schemas/TableTemplateData'
    Table:
      type: object
      required:
      - tableRows
      properties:
        tableHeaders:
          type: array
          items:
            type: string
          example: []
        tableRows:
          type: array
          items:
            type: array
            items:
              type: string
          example: []
        tableFooters:
          type: array
          items:
            type: string
          example: []
    Fdc3Instrument:
      type: object
      required:
      - type
      - name
      properties:
        type:
          type: string
          example: example_value
        name:
          type: string
          example: Example Title
        exchangeMic:
          type: string
          example: example_value
        exchangeMicFds:
          type: string
          example: example_value
        id:
          $ref: '#/components/schemas/InstrumentID'
    RankedTableRow:
      type: object
      required:
      - rank
      properties:
        rank:
          type: number
          example: 42.5
        entity:
          $ref: '#/components/schemas/RankedTableEntity'
        applicationLink:
          $ref: '#/components/schemas/ApplicationLink'
        additionalData:
          type: array
          items:
            type: string
          example: []
    CountryID:
      type: object
      properties:
        ISOALPHA2:
          type: string
          example: example_value
    NoAnswersFound:
      allOf:
      - $ref: '#/components/schemas/NoAnswersBase'
      - type: object
        required:
        - querySuggestions
        properties:
          querySuggestions:
            type: array
            items:
              type: string
    ApplicationLink:
      type: object
      required:
      - name
      - webLink
      properties:
        name:
          type: string
          example: Example Title
        workstationLink:
          type: string
          example: example_value
        webLink:
          type: string
          example: example_value
    Fdc3Context:
      oneOf:
      - $ref: '#/components/schemas/Fdc3Instrument'
      - $ref: '#/components/schemas/Fdc3Country'
      discriminator:
        propertyName: type
        mapping:
          fdc3.instrument: '#/components/schemas/Fdc3Instrument'
          fdc3.country: '#/components/schemas/Fdc3Country'
    ValueLabelDateAnswer:
      allOf:
      - $ref: '#/components/schemas/AnswerWithTitle'
      - type: object
        required:
        - templateData
        properties:
          templateData:
            $ref: '#/components/schemas/ValueLabelDateTemplateData'
    ValueLabelAnswer:
      allOf:
      - $ref: '#/components/schemas/AnswerWithTitle'
      - type: object
        required:
        - templateData
        properties:
          templateData:
            $ref: '#/components/schemas/ValueLabelTemplateData'
    ValueLabelDateTextBlockAnswer:
      allOf:
      - $ref: '#/components/schemas/AnswerWithTitle'
      - type: object
        required:
        - templateData
        properties:
          templateData:
            $ref: '#/components/schemas/ValueLabelDateTextBlockTemplateData'
    ColoredValueLabelDateAnswer:
      allOf:
      - $ref: '#/components/schemas/AnswerWithTitle'
      - type: object
        required:
        - templateData
        properties:
          templateData:
            $ref: '#/components/schemas/ColoredValueLabelDateTemplateData'
    ValueLabelDateTemplateData:
      allOf:
      - $ref: '#/components/schemas/TemplateWithLinks'
      - type: object
        properties:
          value:
            type: string
          label:
            type: string
          date:
            type: string
    AnswerWithoutData:
      allOf:
      - $ref: '#/components/schemas/NoAnswersBase'
      - type: object
        required:
        - title
        - templateData
        properties:
          title:
            type: string
          templateData:
            type: object
            properties:
              fdc3Context:
                $ref: '#/components/schemas/Fdc3Context'
  parameters:
    ConsumingApplication:
      name: consumingApplication
      in: query
      description: Name of application consuming the API (used for analytics purposes)
      required: false
      schema:
        type: string
        default: Developer Portal
    Query:
      name: query
      in: query
      description: Query for desired answer (e.g., "fds price")
      required: true
      schema:
        type: string
  securitySchemes:
    Basic:
      type: http
      scheme: basic
