openapi: 3.2.0
info:
  version: 1.0.0
  title: FactSet Vermilion Instances API
  contact:
    name: FactSet Research Systems
    email: api@factset.com
    url: https://developer.factset.com/contact
  license:
    name: Apache License, Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  description: '

    The Vermilion API, enables users to programmatically access FactSet''s

    Vermilion Reporting Suite (VRS) and seamlessly integrate into customer''s

    3rd party applications. The API is referred to as two key product

    initiatives, the REST API and the SCIM API.'
security:
- FactSetApiKey: []
- FactSetOAuth2: []
tags:
- name: Instances
paths:
  /v1/{tenant}/report-instances:
    get:
      operationId: getAllReportInstances
      tags:
      - Instances
      summary: Factset Gets a List of Report Instances
      description: Gets a list of report instances. This can be filtered down further by including query parameters in the URL. For example, a report definition id can be added so the only report instances returned are the ones with a matching id
      parameters:
      - in: path
        name: tenant
        description: The code of the tenancy
        schema:
          type: string
        required: true
      - in: query
        name: reportDefinitionCode
        description: Acts as a filter for the retrieval process. Filters the report instances that match the report definition code
        schema:
          type: string
      - in: query
        name: entityCodes
        description: 'A series of query parameters used to filter the report instances by entity code. E.g: entityCode=DATE&entityCode=SYSTEM_LANG'
        schema:
          type: string
      - in: query
        name: entityKeys
        description: 'A series of query parameters used to filter the report instances by entity keys. E.g: entityKey=en-gb'
        schema:
          type: string
      - in: query
        name: sectionFilter
        description: Acts as a filter for the retrieval process. Filters the report instances that match the section filter
        schema:
          type: string
      - in: query
        name: outputFormat
        description: Acts as a filter for the retrieval process. Filters the report instances that match the output format
        schema:
          type: string
      - in: query
        name: _sort
        description: The column to sort on. Append - to sort in descending order. If parameter is not given, sorting will be based on the report instance id in descending order
        required: false
        style: form
        explode: false
        schema:
          type: array
          maxItems: 1
          items:
            type: string
        examples:
          reportInstanceId:
            value:
            - reportInstanceId
            description: The id of report instance to sort
          reportStatus:
            value:
            - reportStatus
            description: The status of the report to sort
          startDate:
            value:
            - startDate
            description: The start date of the report to sort
          finishDate:
            value:
            - finishDate
            description: The finish date of the report to sort
          signOffStatus:
            value:
            - signOffStatus
            description: The sign off status of the report to sort
          outputFormat:
            value:
            - outputFormat
            description: The output format of report to sort
      - in: query
        name: _paginationLimit
        description: Non-negative maximum number of entries to return
        schema:
          type: integer
        examples:
          pageSize:
            value: 25
            description: Non-negative maximum number of entries to return
      - in: query
        name: _paginationOffset
        description: Non-negative number of entries to skip
        schema:
          type: integer
        examples:
          startIndex:
            value: 0
            description: Non-negative maximum number of entries to return
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReportInstanceList'
        '401':
          description: Unauthorised
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorList'
              example:
                errors:
                - id: ID of the error
                  code: notAuthenticated
                  title: User is not authenticated
        '403':
          description: No permissions to view reports in VRS
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorList'
              example:
                errors:
                - id: ID of the error
                  code: notAuthorized
                  title: No permissions to view this item
        '406':
          description: Unsupported Accept header. Header needs to be set to application/json.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorList'
              example:
                errors:
                - id: ID of the error
                  code: notAcceptable
                  title: Unsupported Accept header. Header needs to be set to application/json
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  schemas:
    ReportInstanceList:
      type: object
      properties:
        meta:
          type: object
          properties:
            pagination:
              type: object
              properties:
                total:
                  type: integer
                isEstimatedTotal:
                  type: boolean
          example: example_value
        data:
          type: array
          items:
            $ref: '#/components/schemas/ReportInstanceDTO'
          example: []
    ErrorList:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
          example: []
    Error:
      type: object
      properties:
        id:
          type: string
          example: abc123
        code:
          type: string
          example: example_value
        title:
          type: string
          example: Example Title
    ReportRevisionDTO:
      type: object
      properties:
        reportStatus:
          type: string
          enum:
          - WAITING
          - STARTING
          - RETRIEVING_REQUEST
          - CONTENT_FILTER
          - STYLE_PROCESSING
          - RULE_PROCESSING
          - GETTING_DATA
          - RI_PROCESSING
          - COMPILE
          - SUBSTITUTION
          - TRANSLATION
          - GRID_PROCESSING
          - CHART_PROCESSING
          - IMPORTED_FILE_PROCESSING
          - TEXT_PROCESSING_STATUS
          - TOC_PROCESSING_STATUS
          - COMPONENT_PROCESSING
          - POST_PROCESSING
          - POSTING_TO_WRS
          - RENDERING
          - ABORTED
          - COMPLETED
          - COMPLETED_CAUTIONS
          - COMPLETED_ERROR
          - COMPLETED_MODIFYING
          - COMPLETED_CHANGED
          - DELETING
          - REPORT_ORIGINAL_GENERATION
          - REPORT_PREVIOUS_REVISION
          - GENERATING
          example: WAITING
        startDate:
          type: string
          example: example_value
        finishDate:
          type: string
          example: example_value
        signOffStatus:
          type: string
          enum:
          - REJECTED
          - PENDING
          - APPROVED
          example: REJECTED
        signOffNotes:
          type: string
          example: example_value
        reportReasonCd:
          type: string
          example: example_value
        description:
          type: string
          example: A sample description.
        languageCode:
          type: string
          example: example_value
        outputFormat:
          type: string
          example: example_value
        percentageComplete:
          type: integer
          format: int32
          example: 10
    ReportInstanceDTO:
      type: object
      properties:
        reportInstanceId:
          type: integer
          format: int32
          example: '500123'
        reportDefinitionId:
          type: integer
          format: int32
          example: '500123'
        reportDefinitionName:
          type: string
          example: example_value
        reportName:
          type: string
          example: example_value
        userFriendlyReportName:
          type: string
          example: example_value
        extension:
          type: string
          example: example_value
        reportRevision:
          $ref: '#/components/schemas/ReportRevisionDTO'
        name:
          type: string
          example: Example Title
  securitySchemes:
    FactSetOAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://auth.factset.com/as/token.oauth2
          scopes: {}
    FactSetApiKey:
      type: http
      scheme: basic
externalDocs:
  description: API Documentation
  url: https://developer.factset.com/api-catalog/vermilion-api
