openapi: 3.2.0
info:
  title: Factset IRN API v1 Custom Symbol Custom Fields API
  description: Allows users to extract, create, update and configure IRN data.
  version: '1'
servers:
- url: https://api.factset.com/research/irn
  description: Production Server
- url: https://api-sandbox.factset.com/research/irn
  description: Sandbox
security:
- basicScheme: []
tags:
- name: Custom Symbol Custom Fields
paths:
  /v1/custom-symbol-custom-fields:
    get:
      tags:
      - Custom Symbol Custom Fields
      summary: Factset Get all the Custom symbol custom fields
      operationId: GetCustomSymbolCustomFields
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CustomSymbolCustomFieldConfigDto'
    post:
      tags:
      - Custom Symbol Custom Fields
      summary: Factset Create a Custom symbol custom field
      operationId: CreateCustomSymbolCustomField
      requestBody:
        description: createCustomSymbolCustomFieldDto object to save
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/CreateCustomSymbolCustomFieldDto'
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCustomSymbolCustomFieldDto'
          text/json:
            schema:
              $ref: '#/components/schemas/CreateCustomSymbolCustomFieldDto'
          application/*+json:
            schema:
              $ref: '#/components/schemas/CreateCustomSymbolCustomFieldDto'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewItemDto'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
  /v1/custom-symbol-custom-fields/{customSymbolCustomFieldId}:
    get:
      tags:
      - Custom Symbol Custom Fields
      summary: Factset Get a specific Custom symbol custom field's details
      operationId: GetCustomSymbolCustomField
      parameters:
      - name: customSymbolCustomFieldId
        in: path
        description: customSymbolCustomFieldId to get associated record
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomSymbolCustomFieldConfigDto'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
    patch:
      tags:
      - Custom Symbol Custom Fields
      summary: Factset Edit a Custom symbol custom field
      operationId: PatchCustomSymbolCustomField
      parameters:
      - name: customSymbolCustomFieldId
        in: path
        description: customSymbolCustomFieldId to update associated record
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        description: customSymbolCustomFieldUpdateDto object to update
        content:
          application/json-patch+json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Operation'
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Operation'
          text/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Operation'
          application/*+json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Operation'
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
    delete:
      tags:
      - Custom Symbol Custom Fields
      summary: Factset Delete a Custom symbol custom field
      operationId: DeleteCustomSymbolCustomField
      parameters:
      - name: customSymbolCustomFieldId
        in: path
        description: customSymbolCustomFieldId to delete associated record
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
components:
  schemas:
    CustomSymbolCustomFieldConfigDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
        code:
          type:
          - string
          - 'null'
        name:
          type:
          - string
          - 'null'
        type:
          type:
          - string
          - 'null'
        isHidden:
          type: boolean
        isMandatory:
          type: boolean
        isShownInInfobox:
          type: boolean
        formulaConfig:
          $ref: '#/components/schemas/CustomSymbolCustomFieldFormulaConfigDto'
        optionsConfig:
          type:
          - array
          - 'null'
          items:
            type: string
        customSymbolTypes:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/CustomSymbolTypeSummaryDto'
      additionalProperties: false
    NewItemDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
      additionalProperties: false
    OperationType:
      enum:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      type: integer
      format: int32
    Operation:
      type: object
      properties:
        operationType:
          $ref: '#/components/schemas/OperationType'
        path:
          type:
          - string
          - 'null'
        op:
          type:
          - string
          - 'null'
        from:
          type:
          - string
          - 'null'
        value: {}
      additionalProperties: false
    CustomSymbolCustomFieldFormulaConfigDto:
      required:
      - formula
      - formulaType
      type: object
      properties:
        formula:
          maxLength: 2040
          type: string
        formulaType:
          type: string
      additionalProperties: false
    CustomSymbolTypeSummaryDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type:
          - string
          - 'null'
      additionalProperties: false
    CreateCustomSymbolCustomFieldDto:
      required:
      - code
      - customSymbolTypes
      - isHidden
      - isMandatory
      - isShownInInfobox
      - name
      - type
      type: object
      properties:
        code:
          maxLength: 32
          type: string
        name:
          maxLength: 100
          type: string
        type:
          type: string
          description: Type can be one of Text, SingleOption, MultiOptions, Numeric, Date, ExtendedText, ContactLookup
        isHidden:
          type: boolean
          default: false
        isMandatory:
          type: boolean
          default: false
        isShownInInfobox:
          type: boolean
          default: true
        formulaConfig:
          $ref: '#/components/schemas/CustomSymbolCustomFieldFormulaConfigDto'
        optionsConfig:
          type:
          - array
          - 'null'
          items:
            type: string
        customSymbolTypes:
          type: array
          items:
            type: string
            format: uuid
      additionalProperties: false
    ProblemDetails:
      type: object
      properties:
        type:
          type:
          - string
          - 'null'
        title:
          type:
          - string
          - 'null'
        status:
          type:
          - integer
          - 'null'
          format: int32
        detail:
          type:
          - string
          - 'null'
        instance:
          type:
          - string
          - 'null'
      additionalProperties: {}
  securitySchemes:
    basicScheme:
      type: http
      scheme: basic
