openapi: 3.0.3
info:
  title: Factset Analytics Datastore About Relationship API
  description: Allow clients to fetch precalculated Analytics through predeterministic URLs.
  contact:
    name: FactSet Research Systems
    url: https://developer.factset.com/contact
    email: api@factset.com
  license:
    name: Apache License, Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  version: 1.0.0
servers:
- url: https://api.factset.com
  description: Production
- url: https://api-sandbox.factset.com
  description: Sandbox
security:
- basicAuth: []
tags:
- name: Relationship
paths:
  /v1/relationship-categories:
    get:
      tags:
      - Relationship
      summary: Factset Get List of the Relationship Categories Configured in Your Group
      operationId: GetRelationshipCategories
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RelationshipCategoryDto'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
    post:
      tags:
      - Relationship
      summary: Factset Create a Relationship Category
      operationId: CreateRelationshipCategory
      requestBody:
        description: RelationshipCategorySaveDto object to save
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/RelationshipCategorySaveDto'
          application/json:
            schema:
              $ref: '#/components/schemas/RelationshipCategorySaveDto'
          text/json:
            schema:
              $ref: '#/components/schemas/RelationshipCategorySaveDto'
          application/*+json:
            schema:
              $ref: '#/components/schemas/RelationshipCategorySaveDto'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewItemDto'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /v1/relationship-categories/reorder:
    post:
      tags:
      - Relationship
      summary: Factset Reorder Relationship Categories
      operationId: UpdateRelationshipCategoryOrder
      requestBody:
        description: List of Guid
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/RelationshipCategoryListDto'
          application/json:
            schema:
              $ref: '#/components/schemas/RelationshipCategoryListDto'
          text/json:
            schema:
              $ref: '#/components/schemas/RelationshipCategoryListDto'
          application/*+json:
            schema:
              $ref: '#/components/schemas/RelationshipCategoryListDto'
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /v1/relationship-categories/{relationshipCategoryId}:
    put:
      tags:
      - Relationship
      summary: Factset Edit a Relationship Category
      operationId: EditRelationshipCategory
      parameters:
      - name: relationshipCategoryId
        in: path
        description: relationshipCategoryId to update associated record
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        description: RelationshipCategorySaveDto object to update
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/RelationshipCategorySaveDto'
          application/json:
            schema:
              $ref: '#/components/schemas/RelationshipCategorySaveDto'
          text/json:
            schema:
              $ref: '#/components/schemas/RelationshipCategorySaveDto'
          application/*+json:
            schema:
              $ref: '#/components/schemas/RelationshipCategorySaveDto'
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
    delete:
      tags:
      - Relationship
      summary: Factset Delete a Relationship Category
      operationId: DeleteRelationshipCategory
      parameters:
      - name: relationshipCategoryId
        in: path
        description: relationshipCategoryId to delete associated record
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  schemas:
    NewItemDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: abc123
      additionalProperties: false
    RelationshipCategoryDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: abc123
        name:
          type: string
          nullable: true
          example: Example Title
        isStandard:
          type: boolean
          example: true
        isContactToContact:
          type: boolean
          example: true
        isContactToSymbol:
          type: boolean
          example: true
        relationships:
          type: array
          items:
            $ref: '#/components/schemas/RelationshipDto'
          nullable: true
          example: []
      additionalProperties: false
    RelationshipDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: abc123
        relationshipCategoryId:
          type: string
          format: uuid
          example: '500123'
        relationshipCode:
          type: string
          nullable: true
          example: example_value
        bidirectionalName:
          type: string
          nullable: true
          example: example_value
        leftToRightName:
          type: string
          nullable: true
          example: example_value
        rightToLeftName:
          type: string
          nullable: true
          example: example_value
        hideDates:
          type: boolean
          example: true
        hideComment:
          type: boolean
          example: true
        hideCompany:
          type: boolean
          example: true
        isCustomisable:
          type: boolean
          example: true
      additionalProperties: false
    RelationshipCategorySaveDto:
      required:
      - categoryName
      type: object
      properties:
        categoryName:
          maxLength: 50
          minLength: 0
          type: string
          example: example_value
        isContactToContact:
          type: boolean
          default: false
          example: true
        isContactToSymbol:
          type: boolean
          default: false
          example: true
      additionalProperties: false
    RelationshipCategoryListDto:
      required:
      - ids
      type: object
      properties:
        ids:
          type: array
          items:
            type: string
            format: uuid
          example: []
      additionalProperties: false
    ProblemDetails:
      type: object
      properties:
        type:
          type: string
          nullable: true
          example: example_value
        title:
          type: string
          nullable: true
          example: Example Title
        status:
          type: integer
          format: int32
          nullable: true
          example: 10
        detail:
          type: string
          nullable: true
          example: example_value
        instance:
          type: string
          nullable: true
          example: example_value
      additionalProperties: {}
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
externalDocs:
  url: https://developer.factset.com/api-catalog/analytics-datastore-api
  description: API Documentation
