openapi: 3.0.3
info:
  title: Factset Analytics Datastore About Locations API
  description: Allow clients to fetch precalculated Analytics through predeterministic URLs.
  contact:
    name: FactSet Research Systems
    url: https://developer.factset.com/contact
    email: api@factset.com
  license:
    name: Apache License, Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  version: 1.0.0
servers:
- url: https://api.factset.com
  description: Production
- url: https://api-sandbox.factset.com
  description: Sandbox
security:
- basicAuth: []
tags:
- name: Locations
paths:
  /Locations:
    get:
      tags:
      - Locations
      summary: Factset Get a List of Locations.
      security:
      - basicAuth: []
      parameters:
      - $ref: '#/components/parameters/filter'
      - $ref: '#/components/parameters/startIndex'
      - $ref: '#/components/parameters/count'
      - $ref: '#/components/parameters/attributes'
      - $ref: '#/components/parameters/excludedAttributes'
      responses:
        '200':
          $ref: '#/components/responses/locationsSuccess'
        '400':
          $ref: '#/components/responses/invalidFilterError'
        '401':
          $ref: '#/components/responses/unauthorizedError'
        '403':
          $ref: '#/components/responses/forbiddenError'
        '500':
          $ref: '#/components/responses/internalServerError'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /Locations/{id}:
    get:
      tags:
      - Locations
      summary: Factset Get a Location.
      security:
      - basicAuth: []
      parameters:
      - $ref: '#/components/parameters/resourceId'
      responses:
        '200':
          $ref: '#/components/responses/locationSuccess'
        '401':
          $ref: '#/components/responses/unauthorizedError'
        '403':
          $ref: '#/components/responses/forbiddenError'
        '404':
          $ref: '#/components/responses/locationNotFoundError'
        '500':
          $ref: '#/components/responses/internalServerError'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
    put:
      tags:
      - Locations
      summary: Factset Replace a Location.
      security:
      - basicAuth: []
      parameters:
      - $ref: '#/components/parameters/resourceId'
      requestBody:
        $ref: '#/components/requestBodies/locationResource'
      responses:
        '200':
          $ref: '#/components/responses/locationSuccess'
        '400':
          $ref: '#/components/responses/invalidResourceProvidedError'
        '401':
          $ref: '#/components/responses/unauthorizedError'
        '403':
          $ref: '#/components/responses/forbiddenError'
        '404':
          $ref: '#/components/responses/locationNotFoundError'
        '500':
          $ref: '#/components/responses/internalServerError'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
    patch:
      tags:
      - Locations
      summary: Factset Patch a Location (add, Replace, or Remove Attributes of a Location.)
      security:
      - basicAuth: []
      parameters:
      - $ref: '#/components/parameters/resourceId'
      requestBody:
        $ref: '#/components/requestBodies/patchLocationResource'
      responses:
        '200':
          $ref: '#/components/responses/locationSuccess'
        '400':
          $ref: '#/components/responses/invalidPatchRequestError'
        '401':
          $ref: '#/components/responses/unauthorizedError'
        '403':
          $ref: '#/components/responses/forbiddenError'
        '500':
          $ref: '#/components/responses/internalServerError'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  schemas:
    LocationResource:
      type: object
      properties:
        schemas:
          type: array
          items:
            type: string
          example:
          - urn:scim:schemas:extension:FactSet:Core:1.0:Location
        id:
          type: string
          example: '1598276'
          readOnly: true
        externalId:
          type: string
          example: '1598276'
        name:
          type: string
          description: Name of the location.
          readOnly: true
          example: FIN Wealth Management
        description:
          type: string
          description: Description of the location.
          readOnly: true
          example: A sample description.
        address1:
          type: string
          description: First line of location's address.
          readOnly: true
          example: 601 Main Avenue
        address2:
          type: string
          description: Second line of location's address.
          readOnly: true
          example: Factset - First Floor
        address3:
          type: string
          description: Third line of location's address.
          readOnly: true
          example: example_value
        locality:
          type: string
          description: City of location.
          readOnly: true
          example: Norwalk
        region:
          type: string
          description: State or province of location.
          readOnly: true
          example: Connecticut
        postalCode:
          type: string
          description: Postal code of location.
          readOnly: true
          example: 06850
        country:
          type: string
          description: Country of location.
          readOnly: true
          example: United States
        phoneNumber:
          type: string
          description: Phone number of location.
          readOnly: true
          example: example_value
        mainLocation:
          allOf:
          - $ref: '#/components/schemas/LocationResourceReference'
          - readOnly: true
          example: example_value
        meta:
          type: object
          properties:
            resourceType:
              type: string
              example: Location
            created:
              type: string
              example: '2019-02-11T08:44:19+00:00'
            lastModified:
              type: string
              example: '2021-01-12T03:11:13+00:00'
            location:
              type: string
              example: https://api.factset.com/scim/v2/Locations/1598276
          readOnly: true
          example: example_value
    LocationResourceReference:
      type: object
      properties:
        value:
          type: string
          description: Identifier of the Location.
          example: '1598276'
        $ref:
          type: string
          description: The URI corresponding to a SCIM resource that is this Location.
          example: https://api.factset.com/scim/v2/Locations/1598276
        display:
          type: string
          description: A human-readable name, primarily used for display purposes.
          example: FIN Wealth Management
      required:
      - value
    LocationResourceList:
      type: object
      properties:
        schemas:
          type: array
          items:
            type: string
          example:
          - urn:ietf:params:scim:api:messages:2.0:ListResponse
        totalResults:
          type: integer
          example: 1
        Resources:
          type: array
          items:
            $ref: '#/components/schemas/LocationResource'
          example: []
    Patch:
      type: object
      properties:
        schemas:
          type: array
          items:
            type: string
          example: []
        Operations:
          type: array
          items:
            type: object
            properties:
              op:
                type: string
              path:
                type: string
              value:
                type: string
          example: []
  responses:
    invalidResourceProvidedError:
      description: Provided resource contains invalid data.
      content:
        application/scim+json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            schemas:
            - urn:ietf:params:scim:api:messages:2.0:Error
            scimType: invalidValue
            detail: Provided resource contains invalid data.
            status: '400'
    forbiddenError:
      description: User is not authorized to use this API.
      content:
        application/scim+json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            schemas:
            - urn:ietf:params:scim:api:messages:2.0:Error
            detail: FIN_WEALTH-999999 is not authorized to use the FactSet SCIM API.
            status: '403'
    locationsSuccess:
      description: Success.
      content:
        application/scim+json:
          schema:
            $ref: '#/components/schemas/LocationResourceList'
    invalidPatchRequestError:
      description: Patch request invalid.
      content:
        application/scim+json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            schemas:
            - urn:ietf:params:scim:api:messages:2.0:Error
            scimType: invalidValue
            detail: Provided resource contains invalid data.
            status: '400'
    locationNotFoundError:
      description: Location not found.
      content:
        application/scim+json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            schemas:
            - urn:ietf:params:scim:api:messages:2.0:Error
            detail: Location 1598276 was not found.
            status: '404'
    locationSuccess:
      description: Success.
      content:
        application/scim+json:
          schema:
            $ref: '#/components/schemas/LocationResource'
    invalidFilterError:
      description: Invalid filter value provided.
      content:
        application/scim+json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            schemas:
            - urn:ietf:params:scim:api:messages:2.0:Error
            scimType: invalidFilter
            detail: Invalid filter value.
            status: '400'
    internalServerError:
      description: Internal server error.
      content:
        application/scim+json:
          schema:
            $ref: '#/components/schemas/Error'
    unauthorizedError:
      description: User has not been authenticated.
      content:
        application/scim+json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            schemas:
            - urn:ietf:params:scim:api:messages:2.0:Error
            detail: FactSet.net credentials are missing or invalid.
            status: '401'
  parameters:
    resourceId:
      name: id
      description: ID of resource.
      in: path
      schema:
        type: string
      required: true
    filter:
      name: filter
      description: Resource filter string. See [RFC 7644 section 3.4.2.2](https://tools.ietf.org/html/rfc7644#section-3.4.2.2) for syntax. Note this API implementation also supports a non-standard "re" operator for regular expression matching against strings.
      in: query
      schema:
        type: string
      required: false
    startIndex:
      name: startIndex
      description: Result start index. The one-based index of the first result to be returned in the list of resources. For example, to exclude the first two resources, use a *startIndex* value of 3. This parameter has a default value of 1. This index applies *after* any resource filtration has been applied as specified by the *filter* argument.
      in: query
      schema:
        type: integer
      required: false
    attributes:
      name: attributes
      description: Attribute whitelist filter string. A comma-separated list of resource attribute names to be returned in the response, overriding the set of attributes that would be returned by default. Attribute names must be specified in standard attribute notation (see [RFC 7644 section 3.10](https://datatracker.ietf.org/doc/html/rfc7644#section-3.10).) This parameter cannot be used with the *excludedAttributes* parameter.
      in: query
      schema:
        type: string
      required: false
    excludedAttributes:
      name: excludedAttributes
      description: Attribute blacklist filter string. A comma-separated list of resource attribute names to be excluded in the response, overriding the set of attributes that would be returned by default. Attribute names must be specified in standard attribute notation (see [RFC 7644 section 3.10](https://datatracker.ietf.org/doc/html/rfc7644#section-3.10).) This parameter cannot be used with the *attributes* parameter.
      in: query
      schema:
        type: string
      required: false
    count:
      name: count
      description: Maximum resource count. The server will not return more resources than this value, although it may return fewer.
      in: query
      schema:
        type: integer
      required: false
  requestBodies:
    locationResource:
      description: Location resource.
      required: true
      content:
        application/scim+json:
          schema:
            $ref: '#/components/schemas/LocationResource'
    patchLocationResource:
      content:
        application/scim+json:
          schema:
            $ref: '#/components/schemas/Patch'
          example:
            schemas:
            - urn:ietf:params:scim:api:messages:2.0:PatchOp
            Operations:
            - op: replace
              path: externalId
              value:
              - value: exampleExternalId
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
externalDocs:
  url: https://developer.factset.com/api-catalog/analytics-datastore-api
  description: API Documentation
